quiz_proj3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quizes.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
    path('faq/', faq_view, name='faq'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutPage, name='logout'),
    path('register/', registerPage, name='register'),
    path('leaderboard/', leaderboard, name='leaderboard'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view, registerPage, loginPage, logoutPage, leaderboard, faq_view, QuizViewSet


router = DefaultRouter()
router.register(r'quizzes', QuizViewSet)

app_name = 'quizes'

urlpatterns = [
    path('api/', include(router.urls)),
    path('', QuizListView.as_view(), name='main-view'),
    path("login/", loginPage, name="login"),
    path("logout/", logoutPage, name="logout"),
    path('', QuizListView.as_view(), name='main-view'),
    path("register/", registerPage, name="register"),
    path('<int:pk>/', quiz_view, name='quiz-view'),  
    path('<int:pk>/save/', save_quiz_view, name='save-view'),  
    path('<int:pk>/data/', quiz_data_view, name='quiz-data-view'),  
    path('leaderboard/', leaderboard, name='leaderboard'),
    path('faq/', faq_view, name='faq'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    {% block scripts %}
    {% endblock scripts %}

    <title>quiz app| {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Serbian Quiz App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'quizes:leaderboard' %}">Leaderboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'faq' %}">FAQs</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'quizes:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'quizes:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'quizes:faq' %}">FAQs</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    
      {% block content %}
      {% endblock content %}
    </div>
    
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>