quiz_proj3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from quizes.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
    path('faq/', faq_view, name='faq'),
    path('login/', loginPage, name='login'),
    path('logout/', logoutPage, name='logout'),
    path('register/', registerPage, name='register'),
    path('leaderboard/', leaderboard, name='leaderboard'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view, registerPage, loginPage, logoutPage, leaderboard, faq_view, QuizViewSet


router = DefaultRouter()
router.register(r'quizzes', QuizViewSet)

app_name = 'quizes'

urlpatterns = [
    path('api/', include(router.urls)),
    path('', QuizListView.as_view(), name='main-view'),
    path("login/", loginPage, name="login"),
    path("logout/", logoutPage, name="logout"),
    path('', QuizListView.as_view(), name='main-view'),
    path("register/", registerPage, name="register"),
    path('<int:pk>/', quiz_view, name='quiz-view'),  
    path('<int:pk>/save/', save_quiz_view, name='save-view'),  
    path('<int:pk>/data/', quiz_data_view, name='quiz-data-view'),  
    path('leaderboard/', leaderboard, name='leaderboard'),
    path('faq/', faq_view, name='faq'),
]

quizes/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='quizes_user_set',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        verbose_name='groups',
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='quizes_user_set',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        return self.question_set.all()

    class Meta:
        verbose_name_plural = 'Quizes'

quizes/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Creating a user form for register.html page
class createuserform(UserCreationForm):
    class Meta:
        model=User
        fields=['username','password'] 

quizes/views.py
from django.shortcuts import redirect,render
from django.contrib.auth import login,logout,authenticate
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponse, HttpResponseRedirect
from rest_framework import viewsets
from .serializers import QuizSerializer, QuestionSerializer, AnswerSerializer
from .forms import createuserform
from django.db.models import Sum
from django.contrib import messages
from django.urls import reverse


# Register Page
def registerPage(request):
    if request.user.is_authenticated:
        return redirect('/') 
    else: 
        form=createuserform()
        if request.method=='POST':
            form=createuserform(request.POST)
            if form.is_valid() :
                user=form.save()
                return redirect('login')
        context={
            'form':form,
        }
        return render(request,'quizes/register.html',context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'Invalid username or password.')  # Add error message
        context = {}
        return render(request, 'quizes/login.html', context)


# Logout Page
def logoutPage(request):
    logout(request)
    return redirect('/')


def leaderboard(request):
    top_results = Result.objects.values('user__username').annotate(total_score=Sum('score')).order_by('-total_score')[:500]
    total_count = top_results.count()
    context = {
        'top_results': top_results,
        'total_count': total_count,
    }
    return render(request, 'quizes/leaderboard.html', context=context)

def faq_view(request):
    return render(request, 'quizes/faq.html')

# Quiz List View
class QuizListView(ListView):
    model = Quiz 
    template_name = 'quizes/main.html'


# Quiz View
def quiz_view(request, pk):
    if pk == 'favicon.ico':
        # Handle the favicon.ico request here
        return HttpResponse(status=204)  # Return a blank response

    if pk == 'leaderboard':
        # Handle the leaderboard request here
        return leaderboard(request)
    
    if pk == 'faq':
        # Handle the FAQs request here
        return faq_view(request)

    quiz = get_object_or_404(Quiz, pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})


# Quiz Data View
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })


#serialize
class QuizViewSet(viewsets.ModelViewSet):
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer

class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

class AnswerViewSet(viewsets.ModelViewSet):
    queryset = Answer.objects.all()
    serializer_class = AnswerSerializer



# Save Quiz View (requires login)
@login_required
def save_quiz_view(request, pk):
    if not request.user.is_authenticated:
        messages.error(request, 'To get results, you need to be logged in')
        return HttpResponseRedirect(reverse('quizes:login'))

    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        
        # Extract the questions from the POST data
        for k in data_.keys():
            question = Question.objects.get(text=k)
            questions.append(question)

        user = request.user  # Ensure that the user is authenticated
        quiz = get_object_or_404(Quiz, pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

       
       # Evaluate the user's answers and calculate the score
        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})

        score_ = score * multiplier

        # Save the quiz result to the database
        Result.objects.create(quiz=quiz, user=user, score=score_)

        # Return the result as JSON response
        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})

quizes/templates/quizes/faq.html
{% extends "base.html" %}

{% load static %}

{% block title %}
FAQs - Serbian Quiz App
{% endblock title %}

{% block content %}
<h1>Frequently Asked Questions</h1>

<h2>Q:-I forgot my password and can't see the results </h2>
<p>A:-Unfortunately, this is essentially an educational application and service pythonanywhere does not allow me to send emails. If you have such a problem, write to me by mail on <a href="mailto:antonfenrisis@gmail.com">antonfenrisis@gmail.com</a> or <a href="https://t.me/Leonid3">Telegram</a>.</p>


<h2>About Web App</h2>
<p>This is a Quiz Application developed using Django and JavaScript. It allows users to register, log in, and take quizzes with multiple-choice questions. The application calculates the user's score, provides feedback on their answers, and determines if they have passed the quiz based on the set passing score.</p>
<p>Quiz Application allows administrators to create and manage quizzes with customizable multiple-choice questions, answers, and time limits. User authentication and authorization ensure secure access and tailored experiences. The dynamic quiz interface generates real-time updates, providing immediate feedback to users as they navigate through the quiz. A timer adds a sense of urgency, challenging users to complete the quiz within the allotted time. Score calculation and result analysis provide  feedback and determine pass/fail status based on the set passing score. Overall, our Quiz Application stands out with its distinctive features, including customizable quizzes, user authentication, dynamic interface, timer functionality, and comprehensive result analysis, creating a  engaging user experience.<p>
<h2>Repository</h2>
<p>Find the source code of that web app on GitHub:</p>
<a href="https://github.com/fenrisis/quiz_project3" class="btn btn-success">GitHub Repository</a>
<a href="{% url 'quizes:main-view' %}" class="btn btn-primary">Back</a>

{% endblock content %}

quizes/templates/quizes/leaderboard.html
{% extends "base.html" %}

{% load static %}

{% load custom_filters %}

{% block content %}
<div class="container">
    <h1 class="text-center my-4"><span class="badge badge-info"><i class="fa fa-trophy" aria-hidden="true"></i> TOP {{ total_count }} PLAYERS <i class="fa fa-trophy" aria-hidden="true"></i></span></h1>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Position</th>
                <th>Username</th>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            {% for result in top_results %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ result.user__username }}</td>
                <td>{{ result.total_score|round_number }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{% url 'quizes:main-view' %}">Go Back</a>
</div>
{% endblock content %}

quizes/templates/quizes/login.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="container jumbotron">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <form method="POST" action="">
        {% csrf_token %}
        <p><input type="text" name="username" placeholder="Username..."></p>
        <p><input type="password" name="password" placeholder="Password..."></p>
        <input class="btn btn-success" type="submit" value="Login">
        <p>Do not have an account<a href="{% url 'quizes:register' %}">Register</a></p>
    </form>
    <p><a href="{% url 'quizes:faq' %}">FAQs</a></p>
</div>
{% endblock %}

quizes/templates/quizes/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">no</button>
        <button type="button" id="start-button" class="btn btn-success">yes</button>
      </div>
    </div>
  </div>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col">
      <!-- Login and Register links -->
      <div>
        {% if user.is_authenticated %}
          <span class="greet">Hello, {{ user.username }}</span>
        {% endif %}
      </div>
      {% if not user.is_authenticated %}
        <div class="alert alert-warning mt-3">
          To access quiz details and results, please
          <a href="{% url 'quizes:login' %}">Login</a> or
          <a href="{% url 'quizes:register' %}">Register</a>.
        </div>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col">
      <h1>Serbian Quiz List</h1>
      <hr>
      <div class="row quiz-cards">
        {% for obj in object_list %}
          <div class="col-md-4 mb-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ obj.name }}</h5>
                <p class="card-text">Questions: {{ obj.number_of_questions }}</p>
                <p class="card-text">Difficulty: {{ obj.difficulty }}</p>
                <p class="card-text">Time: {{ obj.time }} minutes</p>
                <p class="card-text">Passing Score: {{ obj.required_score_to_pass }}</p>
                <a href="{% url 'quizes:quiz-view' obj.pk %}" class="btn btn-primary">Start Quiz</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
{% endblock css %}

quizes/templates/quizes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
{{ obj.name }}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <b>{{ obj.name }}</b>
        <p>Score to pass: {{ obj.required_score_to_pass }}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">Go Back</a>

{% if not request.user.is_authenticated %}
    <div class="alert alert-warning mt-3">
        To view the results, you need to be logged in.
        <a href="{% url 'quizes:login' %}">Login</a>
        or
        <a href="{% url 'quizes:register' %}">Register</a>
    </div>
{% endif %}

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">Save</button>
</form>
<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}

quizes/templates/quizes/register.html
{% extends "base.html" %}

{% load static%}
{% block content %}
<div class="container jumbotron">
    <form method="POST" action="" >
        {% csrf_token %}
        {{form.as_p}}
       
        <input class="btn btn-success" type="submit" value="Register Account">
    </form>
</div>
{% endblock %}